export function InstructorCoursesPage({ dashboard, onEdit, onToggle }) {
  return <div className="panel-grid courses-grid">{(dashboard?.myCourses || []).map((course) => <article className="course-card card" key={course._id}><div className="course-topline"><span>{course.category}</span><span>{course.published ? 'Published' : 'Draft'}</span></div><h3>{course.title}</h3><p>{course.description}</p><div className="instructor-stats"><span>{course.enrolledStudents} students</span><span>{course.completion}% completion</span><span>Rating {course.rating || 'N/A'}</span></div><div className="action-row"><button className="primary-btn" onClick={() => onEdit(course)} type="button">Edit course</button><button className="secondary-btn" onClick={() => onToggle(course)} type="button">{course.published ? 'Unpublish' : 'Publish'}</button></div></article>)}{!dashboard?.myCourses?.length && <div className="card wide"><h3>No courses yet</h3><p>Create your first course to start teaching.</p></div>}</div>;
}

export function InstructorStudentsPage({ students }) {
  return <div className="card table-card"><div className="section-heading"><h3>Enrolled students</h3><span>{students?.length || 0} enrollments</span></div><div className="data-table"><div className="table-row table-head"><span>Student</span><span>Course</span><span>Progress</span><span>Status</span></div>{(students || []).map((student, index) => <div className="table-row" key={`${student.id}-${index}`}><span><strong>{student.name}</strong><small>{student.email}</small></span><span>{student.course}</span><span>{student.progress}%</span><span>{student.status}</span></div>)}</div></div>;
}

export function InstructorAnalyticsPage({ dashboard }) {
  const analytics = dashboard?.analytics || {};
  const courses = dashboard?.myCourses || [];
  const reviews = dashboard?.reviews || [];

  return <div className="panel-grid instructor-analytics">
    <div className="card highlight wide"><h3>Reviews & Analytics</h3><p>Track course performance and understand what learners are saying about your content.</p><div className="analytics-strip"><span>Total reviews<strong>{reviews.length}</strong></span><span>Average rating<strong>{analytics.rating ?? 0}</strong></span><span>Completion<strong>{analytics.completion ?? 0}%</strong></span><span>Quiz average<strong>{analytics.avgQuizScore ?? 0}%</strong></span></div></div>
    <div className="card wide"><div className="section-heading"><h3>Course performance</h3><span>{courses.length} courses</span></div><div className="data-table"><div className="table-row table-head"><span>Course</span><span>Students</span><span>Completion</span><span>Rating</span></div>{courses.map((course) => <div className="table-row" key={course._id}><span><strong>{course.title}</strong><small>{course.published ? 'Published' : 'Draft'}</small></span><span>{course.enrolledStudents}</span><span>{course.completion}%</span><span>{course.rating || 'No ratings'}</span></div>)}{!courses.length && <p>No courses available for analytics yet.</p>}</div></div>
    <div className="card wide table-card"><div className="section-heading"><h3>Learner reviews</h3><span>{reviews.length} reviews</span></div><div className="data-table"><div className="table-row table-head"><span>Learner</span><span>Course</span><span>Rating</span><span>Review</span></div>{reviews.map((review) => <div className="table-row" key={review._id}><span><strong>{review.student?.name || 'Anonymous'}</strong><small>{review.student?.email || ''}</small></span><span>{review.course?.title || 'Unknown course'}</span><span>{'★'.repeat(review.rating)}<small>{new Date(review.createdAt).toLocaleDateString()}</small></span><span>{review.comment}</span></div>)}{!reviews.length && <p>No learner reviews yet.</p>}</div></div>
  </div>;
}

export function CourseEditorPage({ form, setForm, onSave, editing, onAddSection, onAddLesson }) {
  const updateSection = (sectionIndex, field, value) => setForm({ ...form, sections: form.sections.map((section, index) => index === sectionIndex ? { ...section, [field]: value } : section) });
  const updateLesson = (sectionIndex, lessonIndex, field, value) => setForm({ ...form, sections: form.sections.map((section, index) => index === sectionIndex ? { ...section, lessons: section.lessons.map((lesson, position) => position === lessonIndex ? { ...lesson, [field]: value } : lesson) } : section) });
  return <form className="card course-editor" onSubmit={onSave}><div className="section-heading"><div><span className="badge soft">Course Management</span><h3>{editing ? 'Edit course' : 'Create course'}</h3></div><button className="primary-btn" type="submit">{editing ? 'Save changes' : 'Create course'}</button></div><div className="editor-grid"><label>Title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} required /></label><label>Category<input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} required /></label><label>Level<select value={form.level} onChange={(event) => setForm({ ...form, level: event.target.value })}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Price<input type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /></label></div><label>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} required /></label><div className="section-heading"><h4>Sections & lessons</h4><button className="secondary-btn" onClick={onAddSection} type="button">Add section</button></div>{form.sections.map((section, sectionIndex) => <div className="editor-section" key={sectionIndex}><input value={section.title} onChange={(event) => updateSection(sectionIndex, 'title', event.target.value)} required />{section.lessons.map((lesson, lessonIndex) => <div className="lesson-editor" key={lessonIndex}><input value={lesson.title} onChange={(event) => updateLesson(sectionIndex, lessonIndex, 'title', event.target.value)} required /><textarea value={lesson.content} onChange={(event) => updateLesson(sectionIndex, lessonIndex, 'content', event.target.value)} /></div>)}<button className="secondary-btn" onClick={() => onAddLesson(sectionIndex)} type="button">Add lesson</button></div>)}</form>;
}

export function AdminTablePage({ title, rows, children }) { return <div className="card table-card"><div className="section-heading"><h3>{title}</h3><span>{rows?.length || 0} records</span></div>{children}</div>; }
